spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_ADVERTISED_HOST_NAME}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      